version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: vkfksshdmf0207
      MYSQL_DATABASE: flasksql
      MYSQL_USER: blue
      MYSQL_PASSWORD: vkfksshdmf0207
    ports:
      - "3306:3306"
    restart: always

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
